project: 
  type: book

book: 
  title: "Классическая Механика"
  author: "Ернур Байболатов"

  chapters: 
    - index.qmd
    - measuring.qmd

format:
  html:
    theme:
      light: cosmo
    code-fold: false    

